Check health

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -107,9 +107,36 @@ jobs:
     - name: Start test server
       run: |
         pushd tests/test-server
-        mvn --batch-mode -e exec:exec -s .mvn/settings.xml -Drevision=${{ matrix.coherence_version }} -Dcoherence.groupid=com.oracle.coherence.ce -Dmain=com.tangosol.net.DefaultCacheServer -Dexec.args="-Dtangosol.coherence.proxy.port=12345 -Dcoherence.proxy.port1=3001 -Dtangosol.coherence.proxy.port5=3002 -Dtangosol.coherence.proxy.port4=3003 -Dtangosol.coherence.proxy.port2=3004 -Dtangosol.coherence.proxy.port11=3005 -Dtangosol.coherence.proxy.port12=3006 -Dtangosol.coherence.proxy.port7=3007 -Dtangosol.coherence.proxy.port9=3008 -Dtangosol.coherence.proxy.port8=3009 -Dcoherence.management=all -cp %classpath com.tangosol.net.DefaultCacheServer" &
+        mvn --batch-mode -e exec:exec -s .mvn/settings.xml -Drevision=${{ matrix.coherence_version }} -Dcoherence.groupid=com.oracle.coherence.ce -Dmain=com.tangosol.net.DefaultCacheServer -Dexec.args="-Dtangosol.coherence.proxy.port=12345 -Dcoherence.proxy.port1=3001 -Dtangosol.coherence.proxy.port5=3002 -Dtangosol.coherence.proxy.port4=3003 -Dtangosol.coherence.proxy.port2=3004 -Dtangosol.coherence.proxy.port11=3005 -Dtangosol.coherence.proxy.port12=3006 -Dtangosol.coherence.proxy.port7=3007 -Dtangosol.coherence.proxy.port9=3008 -Dtangosol.coherence.proxy.port8=3009 -Dcoherence.management=all -Dcoherence.health.http.port=33333 -cp %classpath com.tangosol.net.Coherence" &
         sleep 30
         popd
+
+    - name: Retry curl until cluster is ready
+      id: curl_check
+      run: |
+        max_attempts=60
+        attempt=1
+        url="http://localhost:33333/ready"
+        expected_response="200"
+        
+        while [ $attempt -le $max_attempts ]; do
+          response=$(curl -s -o /dev/null -w %{http_code} "$url")
+          echo "Attempt $attempt: Response - $response"
+
+          if [ "$response" != "$expected_response" ]; then
+            echo "Received incorrect response. Retrying..."
+            sleep 5
+          else
+            echo "Correct response received. Exiting..."
+            exit 0
+          fi
+
+          sleep 5
+          attempt=$((attempt + 1))
+        done
+
+        echo "All attempts failed."
+        exit 1  # Fails the step if all attempts fail
 
     # Run Tests
     - name: Run Tests
